# Background and foreground colors
background = #000000
foreground = #fefafa

# Standard colors
palette = 0=#000000
palette = 1=#ff525b
palette = 2=#9dff16
palette = 3=#fff42b
palette = 4=#3f9fff
palette = 5=#f5006b
palette = 6=#f2ff67
palette = 7=#fefafc

# Bright colors
palette = 8=#c3892a
palette = 9=#ff5263
palette = 10=#cfff8e
palette = 11=#fffaa3
palette = 12=#b5dbff
palette = 13=#ff529d
palette = 14=#fcffde
palette = 15=#fefafa
