$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(245, 0, 107, 1)
$font_color = rgba(254, 250, 250, 1)
$placeholder_color = rgba(254, 250, 250, 0.7)
$check_color = rgba(242, 255, 103, 1)
