background            #000000
foreground            #fefafa

# black
color0  #000000
color8  #c3892a

# red
color1  #ff525b
color9  #ff5263

# green
color2  #9dff16
color10 #cfff8e

# yellow
color3  #fff42b
color11 #fffaa3

# blue
color4  #3f9fff
color12 #b5dbff

# magenta
color5  #f5006b
color13 #ff529d

#cyan
color6  #f2ff67
color14 #fcffde

#white
color7  #fefafc
color15 #fefafa


